### ISSUE TITLE
Bug (missing $ sign before variable) in line 155 of my-udev-notify.sh

### ISSUE THREAD

**Issue by funnymn** [dimonomid/my-udev-notify#9]
if [[ notification_icons == true ]]; then

should be

 if [[ $notification_icons == true ]]; then

I was wondering why it isn't showing icons and the problem was traced to this line.

**Comment by dimonomid** [comment]
Thanks @funnymn for finding this 6-year-old bug. I never noticed it since this icons functionality was added by another contributor, and I apparently missed it during code review and I didn't need the icons.

Anyway, should be fixed now (via 3e69ac98910abbfe139ce91e15f90d59758919d1): I verified that my notifications now have icons.

Thanks again!
